// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsTrflxKmwNboWqTxPAjUCvUWw7Iuupdw',
    appId: '1:1023811659555:web:c2d381a45ab94f775d4e96',
    messagingSenderId: '1023811659555',
    projectId: 'classmates-b53a8',
    authDomain: 'classmates-b53a8.firebaseapp.com',
    storageBucket: 'classmates-b53a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6czAVCWrUWU532RML8esssyyeQTy36fA',
    appId: '1:1023811659555:android:b5489aa6e778d4e25d4e96',
    messagingSenderId: '1023811659555',
    projectId: 'classmates-b53a8',
    storageBucket: 'classmates-b53a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFLv49rCcoetP3vzmvVmyD2L8X0yjCrqM',
    appId: '1:1023811659555:ios:b99b2f963ec7c44d5d4e96',
    messagingSenderId: '1023811659555',
    projectId: 'classmates-b53a8',
    storageBucket: 'classmates-b53a8.appspot.com',
    iosClientId: '1023811659555-5n8pqq40d2tgs90r8kmqmk246r1ukjts.apps.googleusercontent.com',
    iosBundleId: 'com.example.classmates',
  );
}
